package:
  name: hydroid_gui
  version: "0.1.0"

source:
  fn: v0.1.0.tar.gz
  url: https://github.com/intbio/HYDROID_GUI/archive/v0.1.0.tar.gz
#  md5: d7936180ad4037962401c2302c1edd19
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  

    - HYDROID_GUI=hydroid.hydroid_gui.py:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - hydroid
    - pyqt
    - billiard

  run:
    - hydroid
    - pyqt
    - billiard

test:
  # Python imports
  comands
    - HYDROID_GUI

 
about:
  home: https://github.com/intbio/HYDROID_GUI
  license: GNU General Public License v2.0
  summary: 'GUI for HYDROID - Python package for analyzing hydroxyl-radical footprinting experiments of protein-DNA complexes (https://github.com/ncbi/HYDROID)'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
